### ISSUE TITLE
Incorrect positioning and variable name detection

### ISSUE THREAD

**Issue by sirhc101** [StefanMaron/vscode-allint#2]
Hello @StefanMaron 

First of all, I really like that you took over AL Lint. In perspective of clean code it's a really good approach and I give it a new try, after I dropped the initial AL Lint because it does not work properly.

However, something seems to be broken in variable name detection:
![image](https://user-images.githubusercontent.com/39621236/89887937-6b1d0a80-dbcf-11ea-9538-490693d5ab22.png)

**Comment by StefanMaron** [comment]
For some reason it highlights the wrong section in code. The warning is probably because of the `_JsonResponse ` variable.

I will look into this, as this is clearly a bug. But for a quick fix you should rename this variable.

**Comment by NKarolak** [comment]
The issue is more complex. I am receiving lots of "Variable names should not contain ..." warnings for objects and procedures without any variables:
![image](https://user-images.githubusercontent.com/34504100/90108956-59607200-dd4b-11ea-9fab-fcef54e8b0e5.png)

and on TestFields:
![image](https://user-images.githubusercontent.com/34504100/90108912-477ecf00-dd4b-11ea-9de4-13b0411e6c7c.png)

And whats' the issue on the global variables here? The "_"?
![image](https://user-images.githubusercontent.com/34504100/90109062-83b22f80-dd4b-11ea-84bd-cd691a4e4575.png)

**Comment by StefanMaron** [comment]
I am currently working on moving the file parsing to c# to make it usable without vs code as well. 
I will review this after I got it working in .Net

**Comment by pri-kise** [comment]
I think one problem of the wrong line is caused by comment lines before the actual warning.
I had one file without comments where the warning were placed at the right position.
In the other file with a docu header the  warnings had exactly this offset.
